version: '3'

services:

  # ---------------------
  # Postgres service
  # ---------------------
  postgres:
    private:
      image: "registry.gitlab.com/kloudnuk/postgres:0.0.1-stg"
    container_name: "pg-stg"
    environment:
      - 'POSTGRES_PASSWORD=linvic2024'
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      kn1:
        name: backend
        external: false
    labels:
      - "postgres"
      - "staging"

  # ---------------------
  # Kloudnuk service
  # ---------------------
  kloudnuk-staging:
    private:
      image: "registry.gitlab.com/kloudnuk/kloudnuk:staging-ubuntu"
    container_name: "kn-stg"
    restart: "always"
    ports:
      - "443:443"
    volumes:
      - "kloudnuk:/nuk/"
    networks:
      kn0:
        name: frontend
        external: true
      kn1:
        name: backend
        external: false
    labels:
      - "kloudnuk"
      - "staging"

volumes:
  postgres-vol:
  kloudnuktest-vol:
